name: Generate and package paper
description: Generate the pdf for the paper and package the source in a zip
inputs:
  title: 
    description: "Name of the project"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Package the latex file
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: ./latex-scripts/src/package.sh ${{ inputs.title }} . ./latex-scripts biber
    - name: Zip up the package
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ${{ inputs.title }}.zip ${{ inputs.title }}
    - name: Upload PDF as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.title }}.pdf
        path: main.pdf
    - name: Get short sha
      id: get_sha
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
    - name: Create a new release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.get_sha.outputs.sha }}
      with:
        draft: false
        prerelease: false
        release_name: ${{ env.sha }}
        tag_name: ${{ env.sha }}
    - name: Upload the paper to the release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: main.pdf
        asset_name: ${{ inputs.title }}.pdf
        asset_content_type: pdf
    - name: Upload the zip to the release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ${{ inputs.title }}.zip
        asset_name: ${{ inputs.title }}.zip
        asset_content_type: zip
